[project]
name = "aspsim"
version = "0.0.2"
authors = [
    {name = "Jesper Brunnström", email = "jesper_brunnstrom@hotmail.com"}
]
readme = "README.md"
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
requires-python = ">=3.14"
dependencies = [
    "aspcore",
    "dill>=0.4.1",
    "pyroomacoustics>=0.9.0",
    "pyyaml>=6.0.3",
    "soundfile>=0.13.1",
    "tikzplotlib-patched",
]

[build-system]
requires = ["uv_build>=0.10.9,<0.11.0"]
build-backend = "uv_build"

[project.urls]
Documentation = "https://sounds-research.github.io/aspsim/"
Repository = "https://github.com/SOUNDS-RESEARCH/aspsim"

[tool.pytest.ini_options]
pythonpath = [
  "src"
]

[tool.uv.sources]
aspcore = { path = "../aspcore", editable = true }
tikzplotlib-patched = { git = "https://github.com/JasonGross/tikzplotlib" }

[tool.ruff.lint]
select = ["D"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"


[dependency-groups]
dev = [
    "hypothesis>=6.151.9",
    "pytest>=9.0.2",
]
