#SIMULATION PARAMETERS
ENDTIMESTEP : 81000
SIMBUFFER : 2000
SIMCHUNKSIZE : 5000

#AUDIO PARAMETERS
SAMPLERATE : 2000
C : 343.0
SPATIALDIMS : 3

# reverb options: "none", "identity", "freespace", "ism", "recorded"
REVERB : ism
ROOMSIZE : [7, 5, 2.5]
ROOMCENTER : [-1, 0, 0]
RT60 : 0.14
MAXROOMIRLENGTH : 512

# ADAPTIVE FILTER PARAMETERS
MICSNR : 200

# PLOTS AND MISC
SAVERAWDATA : false
SAVERAWDATAFREQUENCY : 50
PLOTFREQUENCY : 5
GENSOUNDFIELDATCHUNK : 100000
PLOTOUTPUT : pdf

OUTPUTSMOOTHING : 64

AUTOSAVELOAD : True
