#SIMULATION PARAMETERS
tot_samples : 81000
sim_buffer : 2000
sim_chunk_size : 5000

#AUDIO PARAMETERS
samplerate : 2000
c : 343.0
spatial_dims : 3

# reverb options: "none", "identity", "freespace", "ism", "recorded"
reverb : ism
room_size : [7, 5, 2.5]
room_center : [-1, 0, 0]
rt60 : 0.14
max_room_ir_length : 512

# ADAPTIVE FILTER PARAMETERS
mic_snr : 200

# PLOTS AND MISC
save_raw_data : false
save_raw_data_freq : 50
plot_begin : 0
plot_frequency : 5
plot_output : pdf

output_smoothing : 64

auto_save_load : True
