#SIMULATION PARAMETERS
tot_samples : 1801000
sim_buffer : 5000
sim_chunk_size : 10000

save_source_contributions : False
array_update_freq : 1

#AUDIO PARAMETERS
samplerate : 2000
c : 343.0
spatial_dims : 3

# reverb options: "none", "identity", "freespace", "ism", "recorded"
reverb : ism
room_size : [7, 5, 2.5]
room_center : [-1, 0, 0]
rt60 : 0.45
max_room_ir_length : 1900

# PLOTS AND MISC
plot_begin : 0
export_frequency : 10000
plot_output : pdf

output_smoothing : 1

auto_save_load : True
