#SIMULATION PARAMETERS
ENDTIMESTEP : 35000
SIMBUFFER : 5000
SIMCHUNKSIZE : 2000

#AUDIO PARAMETERS
SAMPLERATE : 2000
C : 343.0
SPATIALDIMS : 3

# reverb options: "none", "identity", "freespace", "ism", "recorded"
REVERB : ism
ROOMSIZE : [7, 5, 2.5]
ROOMCENTER : [-1, 0, 0]
RT60 : 0.24
MAXROOMIRLENGTH : 1024

# ADAPTIVE FILTER PARAMETERS
MICSNR : 40
BLOCKSIZE : 1

# PLOTS AND MISC
SAVERAWDATA : false
SAVERAWDATAFREQUENCY : 50
PLOTFREQUENCY : 5
GENSOUNDFIELDATCHUNK : 100000
PLOTOUTPUT : pdf

OUTPUTSMOOTHING : 2048

AUTOSAVELOAD : True
